# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-spacelift-spaces
  description: This component is responsible for creating and managing the [spaces](https://docs
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
